version: '3.5'

services:
  # proxy:
  #   image: nginx:alpine
  #   container_name: proxy
  #   ports:
  #     - '8080:80'
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf
  #   restart: 'unless-stopped'
  #   networks:
  #     - backend

  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: test
    ports:
      - '3306:3306'
    networks:
      - backend
  redis:
    image: redis
    container_name: "redis"
    command: /bin/sh -c "redis-server --requirepass $$REDIS_HOST_PASSWORD"
    restart: always
    ports:
      - '6380:6379'
    env_file:
      - .env.production.local
  
  minio:
    image: quay.io/minio/minio
    container_name: minio
    restart: always
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - ./minio/data:/data
    command: server /data --console-address ":9001"
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  data:
    driver: local
